plugin: s2_gm_tools.cloud_proba_percentiles.S2Cloudless_percentiles
plugin_config:
  resampling: cubic
  bands: ["oa_s2cloudless_prob"]
  output_bands: ['oa_s2cloudless_prob_pc_5','oa_s2cloudless_prob_pc_10','oa_s2cloudless_prob_pc_25']
  mask_band: "oa_s2cloudless_mask"
  nodata_classes: ["nodata"]
product:
  name: ga_s2cloudless_percentiles_3
  short_name: ga_s2cloudless_percentiles_3 
  version: 0.0.1
  product_family: percentiles
  region_code_format: x{x:03d}y{y:03d}
    
  # -- EO Dataset3 relative section --
  naming_conventions_values: dea_c3
  explorer_path: https://explorer.dea.ga.gov.au/
  classifier: ard
  maturity: final
  collection_number: 3
  
max_processing_time: 3600
job_queue_max_lease: 3600
renew_safety_margin: 60
future_poll_interval: 2
s3_acl: public-read
cog_opts:
  zlevel: 9
apply_eodatasets3: True

# output_location: >-
#   s3://dea-public-data-dev/ga_s2_gm_cyear_3

# # save-tasks options
# input_products: ga_s2am_ard_3-ga_s2bm_ard_3-ga_s2cm_ard_3
# frequency: all
# grid: au_extended_small_10
# temporal_range: 2020--P3Y 
# dataset_filter: >-
#   {"dataset_maturity": "final"}